version: "3.9"
services:
  data-core-v1:
    # data core build information
    build: .
    #image: registry.gitlab.com/soyvolon/datacore:nightly
    volumes:
      # this is going to need to be configured properly at some point.
      - ./docker-data/dc/config:/app/Config
      # needs an image folder volume as well - maybe.
      - ./docker-data/dc/unsafe_uploads:/app/unsafe_uploads
    depends_on:
      - nginx
      - postgres
      - mailserver

  postgres:
    image: "postgres:12"
    restart: always
    env_file: docker-data/db/postgres.env
    ports:
      - "5000:5432"

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.ariabounds.me
    env_file: smtp/mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  nginx:
    image: nginx
    ports:
      - 80:80
      - 433:433
    # restart: always
    volumes:
      - ./docker-data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro