name: Continuous integration
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
          java-version: 11
          # The package type (jre, jdk, jdk+fx)
          java-package: jdk # optional, default is jdk
          # The architecture (x86, x64) of the package.
          architecture: x64 # optional, default is x64
      - name: Install SonarCloud dotnet
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Start SonarCloud analysis
        run: dotnet sonarscanner begin -k:Soyvolon_FiveOhFirstDataCore -d:sonar.host.url="https://sonarcloud.io" -o:soyvolon -d:sonar.login=${{secrets.SONAR_TOKEN}} -d:sonar.branch.name=${GITHUB_REF##*/} -v:${GITHUB_RUN_NUMBER} -d:sonar.cs.opencover.reportsPaths=./testresults/*/coverage.opencover.xml
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" -r ./testresults -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: End SonarCloud analysis
        run: dotnet sonarscanner end -d:sonar.login=${{secrets.SONAR_TOKEN}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
