name: .NET

on:
  workflow_dispatch:
  release:
    types: ['published']

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --output artifact/build/DataCore
    - name: Stop Current Release
      uses: garygrossgarten/github-action-ssh@release
      continue-on-error: true
      with:
        command: ${{ secrets.STOP_SERVICE_CMD }}
        host: ${{ secrets.RELEASE_HOST }}
        username: ${{ secrets.RELEASE_USER }}
        password: ${{ secrets.RELEASE_PASS }}
    - name: Copy Files over SSH
      uses: garygrossgarten/github-action-scp@release
      with:
        local: artifact/build/DataCore/
        remote: ${{ secrets.RELEASE_DEST }}
        host: ${{ secrets.RELEASE_HOST }}
        username: ${{ secrets.RELEASE_USER }}
        password: ${{ secrets.RELEASE_PASS }}
    - name: Start New Release
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: ${{ secrets.START_SERVICE_CMD }}
        host: ${{ secrets.RELEASE_HOST }}
        username: ${{ secrets.RELEASE_USER }}
        password: ${{ secrets.RELEASE_PASS }}
    
